# Generated by Django 5.0.3 on 2024-05-09 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="auteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_auteur", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("num_tel", models.IntegerField(default=0)),
                ("pays", models.CharField(blank=True, max_length=64)),
                ("ville", models.CharField(blank=True, max_length=64)),
                ("matricule", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="creationCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.IntegerField(default=0)),
                ("type_compte", models.CharField(max_length=64, unique=True)),
                ("balance", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="messageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_auteur",
                    models.CharField(help_text="Entrez votre nom", max_length=100),
                ),
                ("image", models.ImageField(blank=True, upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="pensesPositives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TitreP", models.CharField(max_length=200, unique=True)),
                ("contenus", models.TextField(blank=True)),
                (
                    "nom_auteur",
                    models.CharField(help_text="Entrez votre nom", max_length=100),
                ),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titre", models.CharField(max_length=200, unique=True)),
                ("photo", models.ImageField(blank=True, upload_to="images")),
                ("contenus", models.TextField(blank=True)),
                ("prix", models.IntegerField(default=0)),
                ("date_pub", models.DateField(blank=True, null=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.auteur",
                    ),
                ),
            ],
        ),
    ]
