# Generated by Django 5.0.3 on 2024-05-14 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="auteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_auteur", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("num_tel", models.IntegerField(default=0)),
                ("pays", models.CharField(blank=True, max_length=64)),
                ("ville", models.CharField(blank=True, max_length=64)),
                ("matricule", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="creationCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.IntegerField(default=0, unique=True)),
                ("type_compte", models.CharField(max_length=32)),
                ("balance", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="messageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_auteur", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="static/pages/images/")),
                ("date_mes", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="pensesPositives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TitreP", models.CharField(max_length=200, unique=True)),
                ("contenus", models.TextField(blank=True)),
                ("nom_auteur", models.CharField(max_length=100)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titre", models.CharField(max_length=200, unique=True)),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="static/pages/images"),
                ),
                (
                    "fichier_pdf",
                    models.FileField(blank=True, upload_to="documents_pdf"),
                ),
                ("prix", models.IntegerField(default=0)),
                ("date_pub", models.DateField(default=django.utils.timezone.now)),
                (
                    "auteur",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pages.auteur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="achat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_piece", models.IntegerField(default=1)),
                ("Nom", models.CharField(max_length=90)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.IntegerField(default=0)),
                ("pays", models.CharField(blank=True, max_length=90)),
                ("date_achat", models.DateField(default=django.utils.timezone.now)),
                (
                    "matricule",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pages.creationcompte",
                    ),
                ),
                (
                    "nom_livre",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pages.livre",
                    ),
                ),
            ],
        ),
    ]
