# Generated by Django 5.0.3 on 2024-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_auteur', models.CharField(help_text='Entrez votre nom', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('num_tel', models.IntegerField(default=0)),
                ('pays', models.CharField(blank=True, help_text="Entrez votre pays d'origine", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=200, unique=True)),
                ('date_pub', models.DateField(blank=True, null=True)),
                ('contenus', models.TextField(blank=True)),
                ('prix', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True)),
                ('nom_auteur', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pensesPositives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=200, unique=True)),
                ('contenus', models.TextField(blank=True)),
                ('nom_auteur', models.CharField(help_text='Entrez votre nom', max_length=255)),
            ],
        ),
    ]
