# Generated by Django 5.0.3 on 2024-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_pensespositives_contenus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livre",
            name="fichier_pdf",
            field=models.FileField(upload_to="documents_pdf"),
        ),
        migrations.AlterField(
            model_name="livre",
            name="photo",
            field=models.ImageField(upload_to="images"),
        ),
        migrations.AlterField(
            model_name="livre",
            name="prix",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="messageimage",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
