# Generated by Django 5.0.3 on 2024-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_livre_prix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livre",
            name="fichier_pdf",
            field=models.FileField(blank=True, upload_to="documents_pdf"),
        ),
        migrations.AlterField(
            model_name="livre",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
