# Generated by Django 5.0.3 on 2024-05-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_auteur_matricule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pensespositives",
            name="contenus",
            field=models.TextField(),
        ),
    ]
